### ISSUE TITLE
Improvement Roadmap

### ISSUE THREAD

**Issue by AbdelhalimOJ** [yalla-coop/shannon-trust-website#138]
__Further info__

This issue is about improvements that we can apply to the website on Webflow to enhance multiple factors e.g. SEO and Performance

Shannon Trust is currently on the CMS legacy plan, which provides 200GB of bandwidth. Once Webflow ends this plan, they will need to switch to the Business plan to accommodate their current usage, as they exceed 50GB each month.

To reduce costs, we should optimize the usage and track the bandwidth for the next month to see if we can lower it.

- [x] - [ Add Global canonical tag URL ]
- [x] - [ Minify CSS ]
- [x]  - [ Compress all assets to be in AVIF format ]
- [x]  - [ Unpublish empty collection pages to clear the sitemap.xml ]
- [x]  - [ Clear unused styles ]
- [x]  - [ Clear unused interactions ]
- [x]  - [ Fix all issues from audit panel in Webflow in all pages to improve accessibility ]
- [x]  - [ Fix reports links on impact page ]

I will add more to the list above on the go
